services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    image: mongo-db-image:v1
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - my-app-network

  test-app:
    build:
      context: .
      dockerfile: Dockerfile.ol
    image: openliberty-ms:v1
    container_name: openliberty-ms
    depends_on:
      - mongodb
    environment:
      MONGO_HOSTNAME: "mongodb"
      MONGO_PORT: "27017"
      MONGO_DBNAME: "testdb"
      MONGO_USER: "sampleUser"
      MONGO_PASS_ENCODED: "{aes}APtt+/vYxxPa0jE1rhmZue9wBm3JGqFK3JR4oJdSDGWM1wLr1ckvqkqKjSB2Voty8g=="
    ports:
      - "9080:9080"
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge
