# Como base se toma una imagen de Open Liberty que sea ligera.
FROM open-liberty:kernel-slim-java17-openj9

# Copiar configuracion de Open Liberty.
ADD https://raw.githubusercontent.com/BlackPixl/WorkShopDocker/refs/heads/main/server.xml /opt/ol/wlp/usr/servers/defaultServer/

CMD ["server", "run", "defaultServer"]